name: "Tests"

on:
  - pull_request
  - push

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Install SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.OVOS_PHP_LIBRARY }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
         configuration: phpunit.xml.dist
         php_extensions: xdebug
         args: --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          verbose: true
